### PR TITLE
Use new build system in jbrowse/development-tools

### PR DESCRIPTION
**Pull request by garrettjstevens**
This is a companion PR to https://github.com/GMOD/jbrowse-components/pull/2487, and supersedes #16.

It updates to the latest build system provided by `@jbrowse/development-tools`. By default it produces the same bundles as before (with optional CJS and ESM bundles now possible).

Upgrade to rollup v2 also allows some bug fixes. e.g. workarounds like [this](https://github.com/GMOD/jbrowse-components/blob/e5e1a7c2b54a8cb23b7734cf6685160fdfdb57ab/plugins/config/src/FromConfigAdapter/FromConfigSequenceAdapter.ts#L14-L17) are no longer necessary. `postinstall` step is also no longer necessary.

### CODE REVIEW

**Comment by cmdcolin** [comment]
should this be merged now that GMOD/jbrowse-components#2487 is merged?

**Comment by garrettjstevens** [comment]
Probably not until that is released

**Comment by cmdcolin** [comment]
sounds good...if there is a sample plugin that runs a simple node process might be good for reference in developer guide or similar:) nice work on gettin this merged!

**Comment by cmdcolin** [comment]
would it be possible to get an example of a doing something desktop specific using the plugin template?

**Comment by garrettjstevens** [comment]
> would it be possible to get an example of a doing something desktop specific using the plugin template?

Yeah, let me get something together.

**Comment by garrettjstevens** [comment]
This also now includes a much more robust testing setup to replace `tsdx test`, with an example `@testing-library/react` test for the HelloView component.

**Comment by cmdcolin** [comment]
+1 for @testing-library/react style test!

**Comment by garrettjstevens** [comment]
> would it be possible to get an example of a doing something desktop specific using the plugin template?

I think it would be great to get some docs and/or and official example together, but I don't want to delay the next release with those. For now, though, if people are interested they can check out a toy example I've been testing with:

https://github.com/garrettjstevens/jbrowse-plugin-systeminformation

**Comment by cmdcolin** [comment]
sounds good:)

**Pull request merged**
